export const customer = {
	id: '207119551',
	email: 'bob.norman@hostmail.com',
	accepts_marketing: false,
	first_name: 'Bob',
	last_name: 'Norman',
	display_name: 'Bob',
	name: 'Bob Norman',
	phone: '+16136120707',
	address: {
		address1: 'Chestnut Street 92',
		address2: '',
		city: 'Louisville',
		province: 'Kentucky',
		country: 'United States',
		zip: '40202',
		phone: '555-625-1199',
		province_code: 'KY',
		country_code: 'US',
		country_name: 'United States',
	},
	customerLifetimeValue: 100,
	purchaseCount: 25,
	tags: '',
};
